---
title: "Investment Criteria"
author: "Karl Polen"
date: "March 2, 2019"
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(asrsMethods)
library(zoo)
library(lubridate)
```

## ASRS Investment Criteria

ASRS invests in a highly diversified portfolio across public and private markets.  These notes are intended to be helpful in understanding our approach to decision making.

First and foremost, our decision making is in the cotext of our strategic asset allocation.  This document is available at <https://github.com/AZASRS/Strategic-Asset-Allocation-2018>


## Returns and Risk

Returns are compensation for risk taken.  ASRS invests broadly across risk categories with expected returns (as of early 2019) ranging from 2% in cash markets to double digit returns in private market strategies.

Generally speaking, return categories under 6% (approximately) will be populated in public markets.  There are many options to earn low to mid digit single returns in public markets, and there is no reason incur the disadvantages of illiquidity for these categories.

Generally speaking, return categories greater than 10% are populated in private markets.  There are no liquid listed strategies with return expectations above 10%.

Returns in the 6% to 10% range are the most challenging category and of great interest to us.  While ASRS believes public equity returns are above 7.5% in the long run, there is doubt about this in the short run (as of early 2019) because of persistent low risk free rates and current equity market values compared to historic norms.  Consequently, ASRS is actively seeking strategies that will provide net returns in high single digits  (7% to 9%) at acceptable risk and reasonable cost.

Evaluating risk is straight forward in liquid markets.  We use standard statistical methods to look at risk.  We do CAPM analysis against a relevant benchmark and look for statistically significant "alpha" values greater than zero and stable "beta" values consistent with the stated risk of the strategy.  We do rolling or bootstrap CAPM analysis to assess stability of beta.  For equity strategies, we do risk decomposition along style factors to distinguish "alpha" from "alt-beta".  

Typically returns in liquid markets are not normally distributed.  Generally, equity distributions have right skew and fixed income distributions have left skew.  Strategies in equities, therefore, require confidence that you are capturing the high performing outliers.  This is confirmed in recent research finding that only 4% of listed stocks in the CRSP database (all listed US stocks since around 1930) account for all of the excess return in the US stock market.  Fixed income markets are the opposite -- upside is capped and achieving good performance is a function of successfully sreening out the outliers, all of which are on the downside. Real estate is in the middle with extreme outliers either up or down (assuming leverage at or below 50% and enough liquidity to hold across a cycle) relatively rare.

Because this skewness (assymetry) and kurtosis (importance of outliers) are so pronounced and important in investment statistics, we don't end our analysis with CAPM which presumes normality.  We also do bootstrap analysis of excess returns.  (A very good video explanation of bootstrap methods is found at youtube <https://www.youtube.com/watch?v=STGGniMV0jg&list=PLdxWrq0zBgPV3qHLzRzPhnIXB-2gscdxJ> ).  Based on bootstrap methods we construct confidence intervals around sample statistics.  We do not have a target excess return but evaluate excess returns in terms of "information ratios" whih is simply the expected excess return divided by the standard deviation of the excess return.  That's where bootstrapping comes in.  Neither the expected return nor the standard deviation is observable, consequently we estimate it from data by repeated sampling.  The bottom line of what we are looking for is information ratios above .3 and confidence intervals showing at least 60% probability of positive excess return on a one year time frame and 90% probability of positive excess return on a three year time frame.  Having looked at many, many investment propositions these are challenging criteria that few investments meet.

Private markets present a challenge from a data standpoint.  Because the data is generally quarterly and appraisal based, this type of quantitative analysis is cannot be done because of low reliability of appraisal marks and small number of data points.  Many studies have been done attempting to compensate for this (e.g. desmoothing methods) but we have low confidence in these methods and do not use them.  We are not discouraged by this considering that our highest returning strategies are in these markets.  We live with it and accpet the fact that we have to make subjective judgments about risk in these markets.

We compensate for this by using PME methods to evaluate returns in private markets.  Simply put, we select a public index as the closest proxy for the risk taken and compare the returns from the private markets to public markets.  Generally speaking, we expect the private markets return to exceed the public market alternative by 200bp to 300bp per year as compensation for lockup/reduced liquidity and idiosynchratic or concentrated position risk.  We would consider a lower target in intermediate return strategies if we thought the standard deviation around the excess return was exceptionally low.  The methods for comparing public and private returns are tricky because of changing scale and duration of private investments.  The methods we use are described at this posting <https://karlp-asrs.github.io/pme-calcs/>

## Cost

Costs are incredibly important to ASRS.  Since our overall target is to produce excess returns at the total fund level of around 100bp to 200bp per year, costs of 10bp represent 5% to 10% of the target profit we are trying to achieve.  We aggresively manage cost and it rubs us the wrong way whenever somebody suggests we should be tolerant of costs that are "only" a few basis points.

That said, minimizing costs is not the objective function -- earning positive excess returns with reasonable risk charactistics is what we are after.  We evaluate costs as investments in talent and necessary expertise.  And like any other investment, these costs need to bring an appropriate return.

We evaluate cost in terms of "cost effectiveness" which simply is the ratio of gross excess return (gross return of an investment minus its hurdle or benchmark) divided by the aggregate fees paid to achieve that return.  Our target on fee effectiveness on an expected return basis is 2:1.  In other words, if an investment produces a gross excess return of \$3, we don't want to pay more than \$1 in aggregate fees to a sponsor.  On a realized basis, I'd say we can live with a ratio of 1:1, but if a sponsor is taking more than half the excess returns in fees we would consider that strategy a failure and discontinue it.

A suite of tools for analyzing cost in private equity structures is found at this post  <https://karlp-asrs.github.io/waterfallqd/>

## Organizational factors

ASRS partners with external organizations to implement much of its investment program.  In order to minimize risk to ASRS from instability in those organizations, our first line of defense is to underwrite the quality of the organization.  Of course organizations need to have relevant skills for the strategy they are pursuing, but our underwriting goes beyond that.

Organizational culture, while subjective, is the most important factor in understanding the likelihood that an organization will retain its talent and sustain its historic success.  We don't consider ourselves experts in this realm and have put some effort in refining our thinking on this issue in consultation with industrial psychology experts.  The model we use in thinking about organization culture is shown at this site <https://www.denisonconsulting.com/docs/CultureGettingStarted/The_Denison_Model.htm>

While investment people are often pretty hard-nosed and entrepreneurial, having worked with many organizations we find the best results are achieved in organizations that put work in to their culture.  They have good and demanding work environments where people get honest feedback, are given encouragement and mentoring and have opportunities for growth and rewards if they succeed.  Compensation and appropriate sharing of rewards are extremely important.  Succession planning needs to be in place so that the level of talent below founders are not incented to leave and start their own firm.  Research indicates a high level of risk in asset management firms that do not engage in appropriate succession planning and reward sharing with senior management.

As part of organizational assessment, we are looking for strong evidence of a fiduciary mindset.  ASRS is a trust for the benefit of retired teachers who receive an average benefit check of $1500 per month.  Our partners need to grasp the seriousness of that trust relationship.  We negotiate fair compensation agreements with our sponsors and gladly pay that compensation when results are achieved.  When we discern featherbedding favoring the pecuniary interests of the sponsor over the beneficiaries, that is a non-starter for us and we discontinue relationships when these matters cannot be resolved.  Simply put, we expect ambiguities to be resolved in favor of the beneficiaries and we don't compromise on this.

We also take legal steps to protect the interests of ASRS and its beneficiaries from risk factors associated with organizational stability of its counterparties.  We avoid structures with lockups.  We have largely eliminated traditional "closed end fund" structures from our real estate and credit programs where we implement with separate accounts with custom protections including terminable investment periods, liquidation rights and enforceable investment criteria.  We limit our closed end fund exposure to private equity where it is the only reasonably available choice for us.  We mitigate the risk of it by investing in smaller "bite sizes" with a large number of sponsors.

## Conclusion

This approach has served us well. While being demanding, it is flexible enough that we have successfully implemented partnerships with investment managers of the highest quality who have delivered superior results for us.  Over the last 10 years, we have added over \$4 billion in asset value to the ASRS trust compared to what would have been the case with benchmark return.  The performance of ASRS over the last 1, 3, 5 and 10 year periods are all in the top decile of public pension plans.  





